# Generated by Django 6.0.6 on 2026-06-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetassignment',
            old_name='assigned_to',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='assetassignment',
            old_name='notes',
            new_name='remarks',
        ),
    ]
