# Generated by Django 6.0.6 on 2026-06-26 17:24

import django.db.models.deletion
import selfcalls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_call_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Server', 'Server'), ('Network', 'Network'), ('Firewall', 'Firewall'), ('Switch', 'Switch'), ('Router', 'Router'), ('WiFi', 'WiFi'), ('CCTV', 'CCTV'), ('SAP', 'SAP'), ('ERP', 'ERP'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Virtualization', 'Virtualization'), ('VMware', 'VMware'), ('Backup', 'Backup'), ('NAS', 'NAS'), ('Storage', 'Storage'), ('Email', 'Email'), ('Office 365', 'Office 365'), ('Azure', 'Azure'), ('AWS', 'AWS'), ('Database', 'Database'), ('Printer', 'Printer'), ('Security', 'Security'), ('Patch Management', 'Patch Management'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('department', models.CharField(choices=[('IT Infrastructure', 'IT Infrastructure'), ('Network', 'Network'), ('SAP', 'SAP'), ('Security', 'Security'), ('Support', 'Support'), ('Administration', 'Administration')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('planned_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sla_enabled', models.BooleanField(default=True, verbose_name='Enable SLA Tracking')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_self_calls', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_self_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCallActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STATUS', 'Status Changed'), ('COMMENT', 'Comment Added'), ('ATTACHMENT', 'Attachment Uploaded'), ('CLOSED', 'Closed'), ('UPDATE', 'Details Updated')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('self_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='selfcalls.selfcall')),
            ],
            options={
                'verbose_name_plural': 'self call activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SelfCallAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=selfcalls.models.self_call_attachment_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('self_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='selfcalls.selfcall')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_call_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCallComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('self_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='selfcalls.selfcall')),
            ],
        ),
    ]
