# Generated by Django 6.0.6 on 2026-06-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_category_ticketactivity_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network'), ('Printer', 'Printer'), ('Email', 'Email'), ('SAP MM', 'SAP MM'), ('SAP PP', 'SAP PP'), ('SAP FI', 'SAP FI'), ('SAP SD', 'SAP SD'), ('Access Request', 'Access Request')], default='Software', max_length=20),
        ),
    ]
